### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by kyurik5010** [artiomn/cpp-network-tasks#1]
Здравствуйте @artiomn, при выполнении ./run -q выводится ошибка:

> groupadd: GID '20' already exists
> qt.qpa.xcb: could not connect to display :0
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

В скрипте ./run аргумент -q ссылается на путь 'usr/bin/qtcreator'. Если через ./run зайти в образ и пройти по этому пути, то такого исполняемого файла там нет. Он появляется при установке qtcreator через "sudo apt install qtcreator", но проблема остается прежней.

По советам с сайта Qt посмотрел вывод дебагера Qt:

> root@docker-desktop:/usr/src/gb# qtcreator
> QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" ...
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so"
> Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "eglfs"
>         ]
>     },
>     "archreq": 0,
>     "className": "QEglFSIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("eglfs")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so"
> Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "linuxfb"
>         ]
>     },
>     "archreq": 0,
>     "className": "QLinuxFbIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("linuxfb")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so"
> Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "minimal"
>         ]
>     },
>     "archreq": 0,
>     "className": "QMinimalIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("minimal")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so"
> Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "minimalegl"
>         ]
>     },
>     "archreq": 0,
>     "className": "QMinimalEglIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("minimalegl")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so"
> Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "offscreen"
>         ]
>     },
>     "archreq": 0,
>     "className": "QOffscreenIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("offscreen")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so"
> Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "vnc"
>         ]
>     },
>     "archreq": 0,
>     "className": "QVncIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("vnc")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
> Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "xcb"
>         ]
>     },
>     "archreq": 0,
>     "className": "QXcbIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("xcb")
> QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
> loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
> qt.qpa.xcb: could not connect to display :0
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Aborted

Решил что может быть проблема в библиотеке "xcb". По советам с того же ресурса переустановил "libxcb-xinerama0" (ситуацию не поменяло). Вывод ldd:

> root@docker-desktop:/usr/src/gb# ldd /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
> 	linux-vdso.so.1 (0x00007fff043f0000)
> 	libQt5XcbQpa.so.5 => /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5 (0x00007f8dfbb04000)
> 	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f8dfb442000)
> 	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f8dfaef7000)
> 	libstdc++.so.6 => /usr/local/lib64/libstdc++.so.6 (0x00007f8dface3000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8dfab1e000)
> 	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f8dfaad8000)
> 	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f8dfaa13000)
> 	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f8dfa98c000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8dfa96a000)
> 	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f8dfa965000)
> 	libxcb-icccm.so.4 => /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4 (0x00007f8dfa95e000)
> 	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007f8dfa958000)
> 	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f8dfa951000)
> 	libxcb-keysyms.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1 (0x00007f8dfa74e000)
> 	libxcb-randr.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0 (0x00007f8dfa73c000)
> 	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007f8dfa538000)
> 	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f8dfa529000)
> 	libxcb-shape.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007f8dfa524000)
> 	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f8dfa518000)
> 	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f8dfa50e000)
> 	libxcb-xinerama.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xinerama.so.0 (0x00007f8dfa509000)
> 	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007f8dfa4eb000)
> 	libxcb-xinput.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xinput.so.0 (0x00007f8dfa4c7000)
> 	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f8dfa49c000)
> 	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f8dfa290000)
> 	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8dfa14d000)
> 	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f8dfa142000)
> 	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f8dfa124000)
> 	libxkbcommon-x11.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007f8dfa11a000)
> 	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f8dfa0d7000)
> 	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f8df9fa6000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8df9e62000)
> 	libgcc_s.so.1 => /usr/local/lib64/libgcc_s.so.1 (0x00007f8df9e47000)
> 	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f8df9dc0000)
> 	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f8df9d86000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8df9d67000)
> 	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f8df9c7f000)
> 	libmd4c.so.0 => /usr/lib/x86_64-linux-gnu/libmd4c.so.0 (0x00007f8df9c6d000)
> 	libdouble-conversion.so.3 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007f8df9c56000)
> 	libicui18n.so.67 => /usr/lib/x86_64-linux-gnu/libicui18n.so.67 (0x00007f8df9950000)
> 	libicuuc.so.67 => /usr/lib/x86_64-linux-gnu/libicuuc.so.67 (0x00007f8df9767000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8df9761000)
> 	libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007f8df96d5000)
> 	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f8df95fa000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f8dfbc7c000)
> 	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f8df95cb000)
> 	libuuid.so.1 => /usr/lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f8df95c2000)
> 	libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f8df95b4000)
> 	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f8df955d000)
> 	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007f8df9555000)
> 	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8df9550000)
> 	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f8df934a000)
> 	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f8df9333000)
> 	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f8df92be000)
> 	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f8df9206000)
> 	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f8df91d2000)
> 	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f8df91a6000)
> 	libicudata.so.67 => /usr/lib/x86_64-linux-gnu/libicudata.so.67 (0x00007f8df768d000)
> 	libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f8df7668000)
> 	libsystemd.so.0 => /usr/lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f8df75b3000)
> 	libmd.so.0 => /usr/lib/x86_64-linux-gnu/libmd.so.0 (0x00007f8df75a6000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8df759b000)
> 	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f8df7573000)
> 	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f8df754e000)
> 	libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f8df742e000)
> 	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f8df7408000)

**Comment by kyurik5010** [comment]
Не уверен в каком направлении рыть дальше. Советуют еще поковыряться с Xserver, но я не уверен что проблема именно в этом

**Comment by artiomn** [comment]
Здравствуйте, Юрий (@kyurik5010).

Я сейчас перепроверил - всё работает, и образ на dockerhub тот же, что и у меня.

То, что вы не видите бинарника QtCreator, при заходе через `./run` - вполне нормально: в этом случае используется **другой образ** (не `artiomn/gb-qt-creator-image`, а `artiomn/gb-build-image`, в котором нет IDE).

Сначала проверьте, что у вас новый образ.
Потом можете попробовать добавить в строку запуска внутри скрипта `run` следующий параметр: `-e "DISPLAY=:0" `.
И, на всякий случай, запустить так: `DISPLAY=":0" ./run -q`.

Если не сработает, будем разбираться дальше.
